sonar.projectKey=AdrianCxn_gestion-donaciones-is
sonar.organization=adriancxn

# Archivos a analizar y exclusiones necesarias
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,reporte-owasp-zap/**,tests/**

# Ruta al reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8